= Atividades Online Durante a Quarentena
CAMat <camat.usp@gmail.com>
2020-03-19
:toc: macro
:toc-title: Conteúdos
:note-caption: Nota
:icons: font
:stylesheet: adoc-maker.css

Com a determinação da CRUESP, que suspendeu temporariamente as atividades 
escolares presenciais a partir de terça-feira (17), passaram a ser adotadas 
alternativas online para dar continuidade às disciplinas.

Sabendo que estas medidas foram tomadas às pressas e visando auxiliar as(os) 
estudantes, organizamos este site eunindo informações de diversas disciplinas, 
facilitando o acesso, visto que estas não estão todas numa plataforma comum.

As informações foram obtidas através de contato com professores via e-mail e 
resposta do formulário divulgado pelo CAMat à comunidade estudantil do IME. 
Por isso, pedimos compreensão de todas(os) caso não encontrem neste documento 
alguma disciplina ou informação específica. Caso queira colaborar com conteúdo, 
link:https://qrgo.page.link/ENFtn[acesse o formulário.]

O CAMat reforça que o e-mail institucional é o canal de comunicação comumente 
utilizado pelos docentes e, portanto, em momento como este, mais do que antes, 
se faz necessário o uso; cheque diariamente a sua caixa de entrada!

[NOTE]
Você não tem suporte técnico adequado para acompanhar as atividades?
link:https://qrgo.page.link/DRMk5[Comunique o CAMat!]

toc::[]

== Departamento de Matemática

=== MAT0112 - Vetores e Geometria (Turmas 21 e 46)

O professor Ivan Struchiner tem a intenção de repor todas as aulas de 
forma presencial assim que possível "`a não ser que a administração central da 
Universidade impeça essa possibilidade`", além de realizar algumas atividades 
online. 

O professor afirma que está considerando as sequintes alternativas e que está
aberto a sugestões:

. Reuniões via Google Meets. As reuniões serão gravadas e disponibilizadas para 
os alunos.

. Escrever textos, notas de aulas, resolução de exercícios, etc. Esses textos 
seriam postados na homepage do professor.

. Criar um fórum de discussão.

. Responder emails, com ajuda do monitor, de dúvidas.

[horizontal]
Contato do Professor:: ivanstru@gmail.com

=== MAT0164 - Números Inteiros: Uma Introdução à Matemática

A professora Leila Vasconcellos pretende disponibilizar atividades online no 
e-disciplinas, mas não prosseguirá com a matéria conmo ensino à distância.

[horizontal]
Contato da Professora:: leila@ime.usp.br

=== MAT0205 - Cálculo Diferencial e Integral III

O professor Salvador Zanata prosseguirá com a disciplina via Google Hangout 
(apenas chamada de áudio). Segue o link do chat: 
https://meet.google.com/ngw-avbe-asi

[horizontal]
Contato do Professor:: sazanata@ime.usp.br

=== MAT0231 - Àlgebra II para Licenciatura

A professora Leila Vasconcellos pretende disponibilizar atividades online no 
e-disciplinas, mas não prosseguirá com a matéria conmo ensino à distância.

[horizontal]
Contato da Professora:: leila@ime.usp.br

=== MAT0240 - Geometria e Desenho Geométrico II (turma diurno)

O professor Ricardo Bianconi prosseguirá com a disciplina disponibilizando a
apostila do curso do link:https://www.ime.usp.br/mat/0240/[site da disciplina] 
e mantendo contato via e-mail institucional.

De acordo com as orientações do site, a P1 será mantida no dia 02/04.

[horizontal]
Contato do Professor:: bianconi@ime.usp.br

== Departamento de Estatística

=== MAE0217 - Estatística Descritiva

O professor Julio da Motta Singer optou por prosseguir com a disciplina 
utilizando o Google-Meet. A comunicação com a turma está sendo feito através 
da link:https://www.ime.usp.br/~jmsinger/doku.php?id=mae0217[página da disciplina]

[horizontal]
Contato do Professor:: jmsinger@ime.usp.br

=== MAE0314 - Análise Estatística

Atividades suspensas até o retorno das aulas.

=== MAE0317 - Planejamento e Pesquisa I

A professora Viviana Giampaoli seguirá com a disciplina de forma online da 
seguinte forma:

. Para as aulas usará o Google-Meet

. O material da disciplina será disponibilizado no e-desciplinas.

[horizontal]
Contato da Professora:: vivig@ime.usp.br

=== MAE1514 - Estatística no Ensino Básico

A professora Viviana Giampaoli seguirá com a disciplina de forma online da 
seguinte forma:

. Para as aulas usará o Google-Meet

. O material da disciplina será disponibilizado no e-desciplinas.

[horizontal]
Contato da Professora:: vivig@ime.usp.br

== Departamento de Ciência da Computação

=== MAC0110 - Introdução à Computação para Licenciatura (turma diurno)

O professor Denis Deratani Mauá dará continuidade a disciplina por meio de 
vídeo-aulas e exercícios, usando o e-disciplinas.

[horizontal]
Contato do Professor:: ddm@ime.usp.br

=== MAC0218 - Técnicas de Programação II

A disciplina seguirá com aulas online, usando o Google Meet e com material 
adicional no e-disciplinas. O link para cada aula é disponibilizado dentro 
do próprio e-disciplinas.

As aulas online serão gravadas e disponibilizadas para toda a classe.

[horizontal]
Contato do Professor:: gubi@ime.usp.br

=== MAC0427 - Otimização não Linear (Noturno)

O professor afirma que "`continua a dar aulas online, sem grandes 
planejamentos`". Mais informações podem ser encontradas no 
link:https://paca.ime.usp.br/course/view.php?id=1500[PACA].

[horizontal]
Contato do Professor:: ghaeser@ime.usp.br

== Departamento de Matemática Aplicada

=== MAP0151 - Cálculo Numérico e Aplicações

O professor Alexandre Roma está dando continuidade à matéria via Zoom 
(zoom.us).

A comunicação com a turma ocorre por meio do e-disciplinas. O professor pede 
para àqueles que entraram posteriormente enviem um e-mail para roma@ime.usp.br 
para que ele possa adicioná-los manualmente na turma do e-disciplinas.

[horizontal]
Contato do Professor:: alexandre.roma@gmail.com

=== MAP0216 - Introdução à Análise Real

Atividades suspensas até o retorno das aulas.

== Física

=== 4300152 - Medidas Física

Atividades suspensas até o retorno das aulas.

== Educação

=== EDM0400 - Educação especial, Surdos e Libras

Atividades suspensas até o retorno das aulas.

