= Atividades Online Durante a Quarentena
CAMat <camat.usp@gmail.com>
19-03-2020
:favicon: ./favicon.svg
:toc: macro
:toc-title: Conteúdos
:note-caption: Nota
:icons: font
:stylesheet: styles.css

Com a determinação da CRUESP, que suspendeu temporariamente as atividades 
escolares presenciais a partir de terça-feira (17/03), passaram a ser adotadas 
alternativas online para dar continuidade às disciplinas.

Sabendo que estas medidas foram tomadas às pressas e visando auxiliar as(os) 
estudantes, organizamos este site eunindo informações de diversas disciplinas, 
facilitando o acesso, visto que estas não estão todas numa plataforma comum.

As informações foram obtidas através de contato com professores via e-mail e 
resposta do formulário divulgado pelo CAMat à comunidade estudantil do IME. 
Por isso, pedimos compreensão de todas(os) caso não encontrem neste documento 
alguma disciplina ou informação específica. Caso queira colaborar com conteúdo, 
link:https://qrgo.page.link/ENFtn[acesse o formulário.]

O CAMat reforça que o e-mail institucional é o canal de comunicação comumente 
utilizado pelos docentes e, portanto, em momento como este, mais do que antes, 
se faz necessário o uso; cheque diariamente a sua caixa de entrada!

[NOTE]
Você não tem suporte técnico adequado para acompanhar as atividades?
link:https://qrgo.page.link/DRMk5[Comunique o CAMat!]

toc::[]

== Departamento de Matemática

=== MAT0112 - Vetores e Geometria (Turmas 21 e 46)

O professor Ivan Struchiner tem a intenção de repor todas as aulas de 
forma presencial assim que possível "`a não ser que a administração central da 
Universidade impeça essa possibilidade`", além de realizar algumas atividades 
online. 

O professor afirma que está considerando as sequintes alternativas e que está
aberto a sugestões:

. Reuniões via Google Meets. As reuniões serão gravadas e disponibilizadas para 
  os alunos.

. Escrever textos, notas de aulas, resolução de exercícios, etc. Esses textos 
  serão postados na 
  link:https://www.ime.usp.br/~ivanstru/Site/MAT-112-2020_files/COVID-19/[homepage do professor].

. Criar um fórum de discussão.

. Responder emails, com ajuda do monitor, de dúvidas.

[horizontal]
Contato do Professor:: ivanstru@gmail.com

=== MAT0130 - Equações Diferenciais Ordinarias e Aplicações

O professor Antônio Luiz Pereira prossegue com o calendário letivo, utilizando
as seguintes plataformas:

. e-disciplinas para comunicação e disponibilização de material

. Zoom para as aulas em si (vídeo-conferência).

[horizontal]
Contato do Professor:: alpereir@ime.usp.br

=== MAT0105 - Geometria Analítica (Turma 42)

A professora Ana Paula Jahn dará continuidade à disciplina através do 
e-disciplinas.

[horizontal]
Contato da Professora:: anajahn@ime.usp.br

=== MAT0105 - Geometria Analítica (Turma 47 e 48)

O professor Vyacheslav Futorny prosseguirá com a disciplina via Google-Meet.

De acordo com informações do 
link:https://www.ime.usp.br/~futorny/teaching.html[site do professor], as aulas 
online terão início quarta-feira (25/03),às 19:20. O link e código da sala no 
Google-Meet será informado com 20 minutos de antecedência.

[horizontal]
Contato do Professor:: futorny@ime.usp.br

=== MAT0164 - Números Inteiros: Uma Introdução à Matemática

A professora Leila Vasconcellos pretende disponibilizar atividades online no 
e-disciplinas, mas não prosseguirá com a matéria como ensino à distância.

[horizontal]
Contato da Professora:: leila@ime.usp.br

=== MAT0205 - Cálculo Diferencial e Integral III

O professor Salvador Zanata prosseguirá com a disciplina via Google Hangout 
(apenas chamada de áudio). Segue o link do chat: 
https://meet.google.com/ngw-avbe-asi

[horizontal]
Contato do Professor:: sazanata@ime.usp.br

=== MAT0231 - Àlgebra II para Licenciatura

A professora Leila Vasconcellos pretende disponibilizar atividades online no 
e-disciplinas, mas não prosseguirá com a matéria conmo ensino à distância.

[horizontal]
Contato da Professora:: leila@ime.usp.br

=== MAT0240 - Geometria e Desenho Geométrico II (Diurno)

O professor Ricardo Bianconi prosseguirá com a disciplina disponibilizando a
apostila do curso do link:https://www.ime.usp.br/mat/0240/[site da disciplina] 
e mantendo contato via e-mail institucional.

De acordo com as orientações do site, a P1 será mantida no dia 02/04 e será 
aplicada virtualmente tendo as(os) estudantes de 10:00 às 20:00 (horário de 
Brasília) para enviar as respostas via e-mail.

[horizontal]
Contato do Professor:: bianconi@ime.usp.br

=== MAT0264 - Anéis e Corpos

O professor Ivan Shestakov ainda não se pronunciou publicamente sobre essa 
questão. Porém, a um e-mail de um aluno o indagando sobre esta questão, 
respondeu que não ministraria as aulas de forma online.

[horizontal]
Contato do Professor:: shestak@ime.usp.br

=== MAT0310 - Geometria III (Turma 42)

O professor Ricardo Bianconi continuará a disciplina virtualmente. A 
comunicação entre professor e turma ocorre via e-mail institucional e as 
disciplinas e exercícios estão sendo disponibilizadas no 
link:https://www.ime.usp.br/~mat/0310/[site da disciplina].

De acordo com as orientações do site, a P1 será mantida no dia 30/03 e será 
aplicada virtualmente tendo as(os) estudantes de 10:00 às 20:00 (horário de 
Brasília) para enviar as respostas via e-mail.

[horizontal]
Contato do Professor:: bianconi@ime.usp.br

=== MAT0450 - Seminário de Resolução de Problemas

Atividades suspensas até o retorno das aulas presenciais.

Comunicação com as(os) estudantes sendo feito via e-disciplinas.

[horizontal]
Contato do Professor:: alpereir@ime.usp.br

=== MAT2351 - Cálculo para Funções de Várias Variáveis I (Turmas 22 e 47)

Atividades suspensas até o retorno das aulas presenciais.

Há três listas já disponibilizadas na 
link:https://www.ime.usp.br/~dpdias/2020/MAT2351.html[página do professor].

[horizontal]
Contato do Professor:: dpdias@ime.usp.br

=== MAT1500 - Projetos de Estágio (Turma 42)

A professora Daniela Mariz prossegue com as atividades de maneira online
da seguinte forma:

. e-disciplinas para o envio de questionário, exercícios e para comunicação 
  com a turma;

. link:https://www.ime.usp.br/~danim/index.php?target=mat1500[Site da professora] 
  para disponibilizar o material (questionário, exercícios) e o cronograma da 
  disciplina.

[horizontal]
Contato da Professora: danim@ime.usp.br

=== MAT2351 - Cálculo para Funções de Várias Variáveis I (Turma 42)

Atividades suspensas até o retorno das aulas presenciais.

A professora Claudia Cueva Candido está mantendo o contato, para retirar 
dúvidas e compartilhar informações, com as(os) estudantes por meio do 
Google-Meet e link:https://zoom.us[Zoom].

[horizontal]
Contato da Professora:: cueva@ime.usp.br

== Departamento de Estatística

=== MAE1511 - Estatística para Licenciatura I (Turma 42)

Atividades suspensas até o retorno das aulas presenciais.

Aguardando resposta do professor Marcos Magalhães quanto ao canal a ser adotado 
para comunicação com as(os) estudantes durante o período de quarentena.

[horizontal]
Contato do Professor:: marcos@ime.usp.br

=== MAE0217 - Estatística Descritiva

O professor Julio da Motta Singer optou por prosseguir com a disciplina 
utilizando o Google-Meet. A comunicação com a turma está sendo feito através 
da 
link:https://www.ime.usp.br/~jmsinger/doku.php?id=mae0217[página da disciplina]
.

[horizontal]
Contato do Professor:: jmsinger@ime.usp.br

=== MAE0314 - Análise Estatística

Atividades suspensas até o retorno das aulas.

=== MAE0317 - Planejamento e Pesquisa I

A professora Viviana Giampaoli seguirá com a disciplina de forma online da 
seguinte forma:

. Para as aulas usará o Google-Meet

. O material da disciplina será disponibilizado no e-desciplinas.

[horizontal]
Contato da Professora:: vivig@ime.usp.br

=== MAE1514 - Estatística no Ensino Básico

A professora Viviana Giampaoli seguirá com a disciplina de forma online da 
seguinte forma:

. Para as aulas usará o Google-Meet

. O material da disciplina será disponibilizado no e-desciplinas.

[horizontal]
Contato da Professora:: vivig@ime.usp.br

== Departamento de Ciência da Computação

=== MAC0110 - Introdução à Computação para Licenciatura (Turma 42)

O professor Denis Deratani Mauá dará continuidade a disciplina por meio de 
vídeo-aulas e exercícios, usando o e-disciplinas.

[horizontal]
Contato do Professor:: ddm@ime.usp.br

=== MAC0218 - Técnicas de Programação II

A disciplina seguirá com aulas online, usando o Google Meet e com material 
adicional no e-disciplinas. O link para cada aula é disponibilizado dentro 
do próprio e-disciplinas.

As aulas online serão gravadas e disponibilizadas para toda a classe.

[horizontal]
Contato do Professor:: gubi@ime.usp.br

=== MAC0219 - Programação Concorrente e Paralela

Adotando o e-disciplinas e Google-Meet como alternativa online, o professor
Alfredo Goldman dará continuidade às aulas.

[horizontal]
Contato do Professor:: gold@ime.usp.br

=== MAC0323 - Algoritmos e Estruturas de Dados II

O professor Carlos Eduardo Ferreira prosseguirá com o calendário letivo da 
disciplina por meio do Google-Meet.

[horizontal]
Contato do Professor:: cef@ime.usp.br

=== MAC0336 - Criptografia e Segurança de Dados

O professor Routo Terada prosseguirá o calendário letivo com aulas onlines 
através do Google-Meet. O link é disponibilizado um pouco antes do horário de 
aula no link:https://paca.ime.usp.br/login/index.php[PACA].

Para dúvidas e demais informações, há um grupo da disciplina no Telegram: 
t.me/cripto2020ime

[horizontal]
Contato do Professor:: rt@ime.usp.br

=== MAC0425 - Inteligência Artificial

O professor Marcelo Finger prosseguirá com atividades online, adotando o uso do 
Google-Meet.

[horizontal]
Contato do Professor:: mfinger@ime.usp.br

=== MAC0427 - Otimização não Linear (Noturno)

O professor afirma que "`continua a dar aulas online, sem grandes 
planejamentos`". Mais informações podem ser encontradas no 
link:https://paca.ime.usp.br/course/view.php?id=1500[PACA].

[horizontal]
Contato do Professor:: ghaeser@ime.usp.br

=== MAC0439 - Laboratório de Bancos de Dados

A professora Kelly Rosa Braghetto dará continuidade usando as seguintes 
plataformas:

. e-disciplinas

. https://meet.google.com/rpa-nvxe-uyb[Google-Meet]

[horizontal]
Contato da Professora:: kellyrb@ime.usp.br

== Departamento de Matemática Aplicada

=== MAP0151 - Cálculo Numérico e Aplicações

O professor Alexandre Roma está dando continuidade à matéria via Zoom 
(zoom.us).

A comunicação com a turma ocorre por meio do e-disciplinas. O professor pede 
para àqueles que entraram posteriormente enviem um e-mail para roma@ime.usp.br 
para que ele possa adicioná-los manualmente na turma do e-disciplinas.

[horizontal]
Contato do Professor:: alexandre.roma@gmail.com

=== MAP0216 - Introdução à Análise Real

Atividades suspensas até o retorno das aulas.

=== MAP2212 - Laboratório de Computação e Simulação

O professor Julio Stern prossegue com o calendário letivo da disciplina de modo 
virtual. Utiliza o e-disciplinas para disponibilizar o material necessário a 
realização dos EP's.

[horizontal]
Contato do Professor: jstern@ime.usp.br

=== MAP2310 - Métodos Numéricos em Equações Diferenciais I

Os professores Nelson Kuhl e Sergio Muniz unificaram as Turmas 44 e 54. A 
disciplina prosseguirá com calendário letivo através do 
link:https://edisciplinas.usp.br/course/view.php?id=75932[e-disciplinas].

Os professores pedem para àqueles que ainda não acessaram o e-disciplina então 
o façam e respondam a mensagem que foi enviada.

[horizontal]
Contato do Professor Nelson:: kuhl@ime.usp.br

[horizontal]
Contato do Professor Sergio:: smo@ime.usp.br

== Física

=== 4300152 - Medidas Física

Atividades suspensas até o retorno das aulas.

== Educação

=== EDM0400 - Educação especial, Surdos e Libras

Atividades suspensas até o retorno das aulas.

